name: CI for Kventas
run-name: ${{ github.actor }} is building CI - Kventas
on:
  # Selecciono que va a disparar el actions en este caso hacer push y aceptar pull request en la rama master
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Obligatorio usar ese artifact actions/checkout@v4 para que se pase a la rama y traiga los ultimos cambios
      - name: Checkout
        uses: actions/checkout@v4

      # Se una otro artefact para que haga push de la imagen a docker hub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: cristhiankr/pluss_worket:prod
